version: 1.1.0.{build}
environment:
  stage: alpha
  solution_path: src\Analyzer1.sln
  release_notes: 'It is fine today.'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: >-
    $VERSION = $env:APPVEYOR_BUILD_VERSION

    $STAGE = $env:stage


    $vs = $VERSION -split "\."

    $env:nupkg_version = $vs[0] + "." + $vs[1] + "." + $vs[2]

    $env:is_prelease = "true"

    if($STAGE -ne "release"){
        $env:nupkg_version = $env:nupkg_version + "-" + $STAGE

        $env:is_prelease = "false"
    }


    # rewrite

    $nuspec = (ls $env:APPVEYOR_BUILD_FOLDER -Recurse).Where{ $_.Extension -eq ".nuspec"} | Select -First 1

    [xml]$xml = Get-Content $nuspec.FullName

    $xml.package.metadata.version = $env:nupkg_version

    $xml.package.metadata.releaseNotes = $env:release_notes

    $xml.Save($nuspec.FullName)


    nuget restore $env:solution_path



    Remove-Item "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Amazon Web Services LLC" -Recurse -Force
build:
  project: $(solution_path)
  verbosity: minimal
after_build:
- ps: >-
    $folder = $env:APPVEYOR_BUILD_FOLDER + "\" + ($env:solution_path -split "\.")[0]

    (Get-ChildItem $folder -Recurse).Where{ $_.Extension -eq ".nupkg"} | %{ Push-AppveyorArtifact $_.FullName -FileName $_.Name }
deploy:
  provider: GitHub
  tag: $(nupkg_version)
  release: $(nupkg_version)
  auth_token:
    secure: ld1RBkNTi/7LQRJhZJXjATWL/TdysxJRPcTjyKVvsnLumE7ulNyIUy40eASxX4bv
  draft: false
  prerelease: $(is_prelease)
  on:
    branch: master
    appveyor_repo_tag: true