version: 2.0.0.{build}
environment:
  stage: alpha
  release_notes: 'Stunning New.'
  solution_path: src\Analyzer1.sln
  test_dll_dir: src\Analyzer1\Analyzer1.Test\bin\Release
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: . .\before_build.ps1
build:
  project: $(solution_path)
  verbosity: minimal
after_build:
- ps: . .\after_build.ps1
test_script:
- ps: . .\test.ps1
deploy:
- provider: GitHub
  tag: $(nupkg_version)
  release: $(nupkg_version)
  description: $(release_notes)
  auth_token:
    secure: ld1RBkNTi/7LQRJhZJXjATWL/TdysxJRPcTjyKVvsnLumE7ulNyIUy40eASxX4bv
  prerelease: $(is_prerelease)
  on:
    branch: master